FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
# eventualmente usare un file conf diverso piu specifico per production
# (attualmente in conf viene definita la direttiva per il
# server websocket di sviluppo, non necessario in production)
